
select * from customer limit 20;

-- Q1. What is the total generated by male vs. female customers?
 select gender, sum(purchase_amount) as revenue
from customer 
group by Gender;
 
  
-- Q2. Which are the used a discount but still spent more than the average purchase amount?
 select customer_id , purchase_amount
  from customer
  where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased ,round(avg(review_rating),2) as " Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q.4 Compare the average Purchase Amount between Standard and Express Shipping?
select shipping_type, 
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

-- Q.5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-Suscribers?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by sum(purchase_amount)desc,
avg(purchase_amount) desc;

-- Q.6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' Then 1 else 0 end) /count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q.7 Segment customers into New , Returning, and loyal based on their total number of Previous Purchases, and show the count of each segment?
with customer_type as (
select customer_id , previous_purchases,
case
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then ' Returning'
     else 'Loyal'
     end as customer_segment
     from customer
     )
     select customer_segment, count(*) as "Number of Customers"
     from customer_type
     group by customer_segment;

-- Q.8 What are the top 3 most purchased products within each category?
SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE item_rank <= 3;


-- Q.9 Are customer who are repeat buyers ( more than 5 previous purchases) also likely to subsribe?
select subscription_status,
count(*) as total_customers
from customer 
where Previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?
select Age,
sum(purchase_amount) as total_revenue
from customer
group by Age
order by total_revenue desc;